### ISSUE TITLE
Extension does not work with SQLAlchemy 0.8 (needed for Ckan on Ubuntu 14.04)

### ISSUE THREAD

**Issue by Hoedic** [ckan/ckanext-pages#12]
For various reasons, SQLAlchemy 0.8 is needed to run CKAN 2.2 on Ubuntu 14.04. Unfortunately, it seems that the current code of ckanext-pages is not compatible with version 0.8.

The affected code (at least where it fails) is in db.py, L88:

```
    if isinstance(obj, sa.engine.base.RowProxy):
        fields = obj.keys()
    else:
        ModelClass = obj.__class__
        table = class_mapper(ModelClass).mapped_table
        fields = [field.name for field in table.c]
```
Error looks like: 

```
File '/usr/lib/ckan/ckandev/src/ckanext-pages/ckanext/pages/db.py', line 88 in table_dictize
if isinstance(obj, sa.engine.base.RowProxy):
AttributeError: 'module' object has no attribute 'RowProxy'
```
It seems that RowProxy does not exist anymore in 0.8.

**Comment by joetsoi** [comment]
`sa.engine.base.RowProxy` was moved to `sa.engine.RowProxy`
